export enum SettingActionTypes {
  ACTION_LANGUAGE_SET = 'ACTION_LANGUAGE_SET',
  ACTION_UPDATE_SETTING = 'ACTION_UPDATE_SETTING',
  ACTION_TOGGLE_DEVICE = 'ACTION_TOGGLE_DEVICE',
  ACTION_TOGGLE_SIDEBAR = 'ACTION_TOGGLE_SIDEBAR',
}
