export enum SettingActionTypes {
  ACTION_TOGGLE_SETTING = 'ACTION_TOGGLE_SETTING',
  ACTION_FIX_HEADER = 'ACTION_FIX_HEADER',
  ACTION_FIX_TAGVIEW = 'ACTION_FIX_TAGVIEW',
  ACTION_MENU_MODE = 'ACTION_MENU_MODE',
}
