export enum UserMutationTypes {
  SET_USER_NAME = 'SET_USER_NAME',
  SET_TOKEN = 'SET_TOKEN',
  SET_INTRODUCE = 'SET_INTRODUCE',
  SET_AVATAR = 'SET_AVATAR',
  SET_EMAIL = 'SET_EMAIL',
  SET_ROLES = 'SET_ROLES',
  SET_USER_INFO = 'SET_USER_INFO',
}
