export enum OrderActionTypes {
  ACTION_ORDER_LIST = 'ACTION_ORDER_LIST',
  ACTION_ORDER_SET = 'ACTION_ORDER_SET',
  ACTION_ORDER_DETAIL = 'ACTION_ORDER_DETAIL',
  ACTION_ORDER_LOG = 'ACTION_ORDER_LOG',

  ACTION_OTHER_PAY_LIST = 'ACTION_OTHER_PAY_LIST',
  ACTION_OTHER_PAY_SET = 'ACTION_OTHER_PAY_SET',
  ACTION_OTHER_PAY_DEL = 'ACTION_OTHER_PAY_DEL',
}
