export enum StaffActionTypes {
  ACTION_STAFF_FETCH = 'ACTION_STAFF_FETCH',
  ACTION_STAFF_SELECT_FETCH = 'ACTION_STAFF_SELECT_FETCH',
  ACTION_STAFF_CREATE = 'ACTION_STAFF_CREATE',
  ACTION_STAFF_UPDATE = 'ACTION_STAFF_UPDATE',
  ACTION_STAFF_DELETE = 'ACTION_STAFF_DELETE',
}