export enum AppActionTypes {
  ACTION_TOGGLE_SIDEBAR = 'ACTION_TOGGLE_SIDEBAR',
  ACTION_TOGGLE_DEVICE = 'ACTION_TOGGLE_DEVICE',
  ACTION_SET_LANGUAGE = 'ACTION_SET_LANGUAGE',
  ACTION_CLOSE_SIDEBAR = 'ACTION_CLOSE_SIDEBAR',

  ACTION_MALL_CONFIG = 'ACTION_MALL_CONFIG',
  ACTION_MALL_PHONE_LIST = 'ACTION_MALL_PHONE_LIST',
  ACTION_MALL_PHONE_SET = 'ACTION_MALL_PHONE_SET',
  ACTION_MALL_PHONE_DEL = 'ACTION_MALL_PHONE_DEL',
  ACTION_MALL_ACTIVE_SET = 'ACTION_MALL_ACTIVE_SET',
  ACTION_MALL_MINIAPP_SET = 'ACTION_MALL_MINIAPP_SET',
  ACTION_MALL_REFUND_SET = 'ACTION_MALL_REFUND_SET',
  ACTION_MALL_SMS_SET = 'ACTION_MALL_SMS_SET',
  ACTION_MALL_SMS_GET = 'ACTION_MALL_SMS_GET',
}
