export enum AppMutationTypes {
  TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR',
  TOGGLE_DEVICE = 'TOGGLE_DEVICE',
  SET_LANGUAGE = 'SET_LANGUAGE',


  MALL_CONFIG = 'MALL_CONFIG',
  MALL_PHONE_LIST = 'MALL_PHONE_LIST',
  MALL_PHONE_SET = 'MALL_PHONE_SET',
  MALL_ACTIVE_SET = 'MALL_ACTIVE_SET',
  MALL_MINIAPP_SET = 'MALL_MINIAPP_SET',
  MALL_REFUND_SET = 'MALL_REFUND_SET',
  MALL_SMS_SET = 'MALL_SMS_SET',
}
