export enum SourceActionTypes {
  ACTION_SOURCE_PIC_TYPE_LIST = 'ACTION_SOURCE_PIC_TYPE_LIST',
  ACTION_SOURCE_PIC_TYPE_SET = 'ACTION_SOURCE_PIC_TYPE_SET',
  ACTION_SOURCE_PIC_TYPE_DEL = 'ACTION_SOURCE_PIC_TYPE_DEL',

  ACTION_SOURCE_PIC_BY_TYPE = 'ACTION_SOURCE_PIC_BY_TYPE',
  ACTION_SOURCE_PIC_LIST = 'ACTION_SOURCE_PIC_LIST',
  ACTION_SOURCE_PIC_UPLOAD = 'ACTION_SOURCE_PIC_UPLOAD',
  ACTION_SOURCE_PIC_DEL = 'ACTION_SOURCE_PIC_DEL',

  ACTION_SOURCE_OSS_PIC_URL = 'ACTION_SOURCE_OSS_PIC_URL',
  ACTION_SOURCE_OSS_PIC_DEL = 'ACTION_SOURCE_OSS_PIC_DEL',
}