export enum ProductActionTypes {
  // 产品列表
  ACTION_PRODUCT_LIST = 'ACTION_PRODUCT_LIST',
  ACTION_PRODUCT_SET = 'ACTION_PRODUCT_SET',
  ACTION_PRODUCT_DEL = 'ACTION_PRODUCT_DEL',

  // 产品标签
  ACTION_PRODUCT_TAG_LIST = 'ACTION_PRODUCT_TAG_LIST',
  ACTION_PRODUCT_TAG_SET = 'ACTION_PRODUCT_TAG_SET',
  ACTION_PRODUCT_TAG_DEL = 'ACTION_PRODUCT_TAG_DEL',

  // 产品分类
  ACTION_PRODUCT_CATE_LIST = 'ACTION_PRODUCT_CATE_LIST',
  ACTION_PRODUCT_CATE_SET = 'ACTION_PRODUCT_CATE_SET',
  ACTION_PRODUCT_CATE_DEL = 'ACTION_PRODUCT_CATE_DEL',
}
