export enum ProductMutationTypes {
  PRODUCT_LIST = 'PRODUCT_LIST',
  PRODUCT_ITEM = 'PRODUCT_ITEM',

  PRODUCT_TAG_LIST = 'PRODUCT_TAG_LIST',
  PRODUCT_TAG_ITEM = 'PRODUCT_TAG_ITEM',

  PRODUCT_CATE_LIST = 'PRODUCT_CATE_LIST',
  PRODUCT_CATE_ITEM = 'PRODUCT_CATE_ITEM',
}
