export enum ProductMutationTypes {
  PRODUCT_DATA = 'PRODUCT_DATA',
  PRODUCT_ITEM = 'PRODUCT_ITEM',
  PRODUCT_ITEM_UPDATE = 'PRODUCT_ITEM_UPDATE',

  PRODUCT_STOCK_LIST = 'PRODUCT_STOCK_LIST',
  PRODUCT_STOCK_ITEM = 'PRODUCT_STOCK_ITEM',

  PRODUCT_TAG_LIST = 'PRODUCT_TAG_LIST',
  PRODUCT_TAG_ITEM = 'PRODUCT_TAG_ITEM',

  PRODUCT_CATE_LIST = 'PRODUCT_CATE_LIST',
  PRODUCT_CATE_ITEM = 'PRODUCT_CATE_ITEM',

  PRODUCT_RESOURCE_ALL = 'PRODUCT_RESOURCE_ALL',
}
